#
# Copyright (C) 2016-17 Microsemi Corporation.
# Padmarao Begari, Microsemi Corporation <padmarao.begari@microsemi.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= cache.o cpu.o timer.o interrupts.o


