#
# Copyright (C) 2017 Microsemi Corporation.
# Padmarao Begari, Microsemi Corporation <padmarao.begari@microsemi.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

head-y := arch/riscv/cpu/$(CPU)/start.o

libs-y += arch/riscv/cpu/$(CPU)/
libs-y += arch/riscv/lib/
