#
# Copyright (c) 2016 Microsemi Corporation.
# Copyright (c) 2016 Padmarao Begari <Padmarao.Begari@microsemi.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

extra-y	= start.o

obj-$(if $(filter m2sxxx,$(SOC)),y) += riscv_m2sxxx/
