#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# Copyright (c) 2016 Microsemi Corporation.
# Padmarao Begari, Microsemi Corporation <padmarao.begari@microsemi.com>
# 
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_CMD_BOOTM) += bootm.o
